version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-crispy-forms
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
